version: '3'

services:
  prometheus:
    image: prom/prometheus
    restart: "unless-stopped"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus-data:/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    restart: "unless-stopped"
    volumes:
      - ./grafana-data:/var/lib/grafana